Add `work_macos_m3` environment file Enhance `unison_start` script to support `single_dir` mode

diff --git a/Terminal/DotFiles/.zsh/scripts/unison_start b/Terminal/DotFiles/.zsh/scripts/unison_start
--- a/Terminal/DotFiles/.zsh/scripts/unison_start
+++ b/Terminal/DotFiles/.zsh/scripts/unison_start
@@ -8,8 +8,6 @@
 # Example Usage : ./unison_start
 #----------------
 
-source "$HOME/.zsh/env/common"
-
 main() {
   local mode="$1"
 
@@ -21,16 +19,27 @@ main() {
   local sync_file_location="$ZSCRIPTS/unison_sync"
   local server_domain="$lb_server_domain"
   local user="$lb_username"
+  local server_bin_dir="/usr/bin"
   local local_sync_dir="$SNC"
   local server_sync_dir="/home/${user}/bnk/snc"
-  local server_bin_dir="/usr/bin"
+  local local_lg_dir="$SLG"
+  local server_lg_dir="/home/${user}/bnk/snc/Lg"
 
   if [[ "$mode" == "watch" ]]; then
     nohup "$sync_file_location" "$server_domain" "$user" "$local_sync_dir" "$server_sync_dir" "$server_bin_dir" "watch" >/dev/null 2>&1&
+  elif [[ "$mode" == "single_dir" && ! -z "$dir" ]]; then
+    local snc_dir="$SNC/$dir"
+    if [[ -d "$snc_dir" ]]; then
+      "$sync_file_location" "$server_domain" "$user" "$local_lg_dir" "$server_lg_dir" "$server_bin_dir" "$snc_dir"
+    else 
+      echo "ERROR: Must a preexisting SNC directory to unison_start." >&2
+      echo "Directory $snc_dir not found" >&2
+    fi
+  elif [[ "$mode" == "all" ]]; then
+    "$sync_file_location" "$server_domain" "$user" "$local_lg_dir" "$server_lg_dir" "$server_bin_dir" "$dir"
   else
-    "$sync_file_location" "$server_domain" "$user" "$local_sync_dir" "$server_sync_dir" "$server_bin_dir"
+    echo "ERROR: Must provide valid arguments to unison_start" >&2
   fi
 }
 
 main "$@"
-
